
import React from 'react';
import { 
  ArrowUpRight, 
  ArrowDownRight, 
  Zap, 
  Calendar,
  CreditCard,
  TrendingUp,
  Cpu,
  // Added missing imports for StatCard icons
  Wallet,
  Package
} from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
// Fixed: useApp hook will now be exported from App.tsx
import { useApp } from '../App';

const yieldData = [
  { name: 'Mon', income: 450 },
  { name: 'Tue', income: 820 },
  { name: 'Wed', income: 710 },
  { name: 'Thu', income: 980 },
  { name: 'Fri', income: 1200 },
  { name: 'Sat', income: 1100 },
  { name: 'Sun', income: 1450 },
];

const StatCard = ({ title, value, change, icon: Icon, color }: any) => (
  <div className="glass-effect p-6 rounded-2xl">
    <div className="flex justify-between items-start mb-4">
      <div className={`p-3 rounded-xl bg-${color}-500/10 text-${color}-500`}>
        <Icon className="w-6 h-6" />
      </div>
      <div className={`flex items-center gap-1 text-xs font-bold ${change.startsWith('+') ? 'text-emerald-500' : 'text-rose-500'}`}>
        {change}
        {change.startsWith('+') ? <ArrowUpRight className="w-3 h-3" /> : <ArrowDownRight className="w-3 h-3" />}
      </div>
    </div>
    <h3 className="text-slate-400 text-sm mb-1">{title}</h3>
    <p className="text-2xl font-bold text-white">{value}</p>
  </div>
);

const DashboardView: React.FC = () => {
  const { user } = useApp();

  // Fixed: Add safety check for nullable user and correct property names (balance, withdrawableBalance)
  if (!user) return null;

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      {/* Top Banner */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-800 p-8 text-white shadow-2xl">
        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <h1 className="text-3xl font-bold mb-2">Prime Drink Industrial Hub</h1>
            <p className="text-indigo-100/80 max-w-md">Access premium beverage production equipment leasing. Earn high-yield daily income with low industrial risk.</p>
            <div className="mt-6 flex gap-4">
              <button className="bg-white text-indigo-600 px-6 py-2.5 rounded-xl font-bold hover:bg-slate-100 transition-colors shadow-lg">
                Lease Asset
              </button>
              <button className="border border-white/30 text-white px-6 py-2.5 rounded-xl font-bold hover:bg-white/10 transition-colors">
                View Reports
              </button>
            </div>
          </div>
          <div className="hidden lg:flex items-center gap-4">
            <Cpu className="w-24 h-24 text-white/20" />
          </div>
        </div>
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full blur-3xl -mr-20 -mt-20"></div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard 
          title="Current Wallet" 
          // Fixed: property names to match User interface (balance)
          value={`₹${(user.balance || 0).toLocaleString()}`} 
          change="+12.4%" 
          icon={CreditCard} 
          color="indigo" 
        />
        <StatCard 
          title="Withdrawal Wallet" 
          // Fixed: property names to match User interface (withdrawableBalance)
          value={`₹${(user.withdrawableBalance || 0).toLocaleString()}`} 
          change="+8.2%" 
          icon={Wallet} 
          color="emerald" 
        />
        <StatCard 
          title="Total Yield" 
          value="₹45,200.00" 
          change="+24.1%" 
          icon={Zap} 
          color="amber" 
        />
        <StatCard 
          title="Active Plans" 
          value="4 Units" 
          change="Stable" 
          icon={Package} 
          color="blue" 
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Yield Chart */}
        <div className="lg:col-span-2 glass-effect rounded-3xl p-8">
          <div className="flex items-center justify-between mb-8">
            <div>
              <h3 className="text-xl font-bold text-white">Daily Yield Engine</h3>
              <p className="text-slate-400 text-sm">Revenue generated by leased machinery assets</p>
            </div>
            <select className="bg-slate-800 border-none rounded-lg text-sm px-3 py-1 text-slate-300 focus:ring-0">
              <option>Last 7 Days</option>
              <option>Last 30 Days</option>
            </select>
          </div>
          <div className="h-80 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={yieldData}>
                <defs>
                  <linearGradient id="colorIncome" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#6366f1" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#6366f1" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#1e293b" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12}} />
                <YAxis axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12}} />
                <Tooltip 
                  contentStyle={{backgroundColor: '#0f172a', border: '1px solid #1e293b', borderRadius: '12px'}}
                  itemStyle={{color: '#fff'}}
                />
                <Area type="monotone" dataKey="income" stroke="#6366f1" strokeWidth={3} fillOpacity={1} fill="url(#colorIncome)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* System Activity */}
        <div className="glass-effect rounded-3xl p-8">
          <h3 className="text-xl font-bold text-white mb-6">Recent Activity</h3>
          <div className="space-y-6">
            {[
              { label: 'Yield Distributed', time: '2h ago', amount: '+₹450.00', color: 'emerald' },
              { label: 'Asset Lease: Bottle Capper', time: '1d ago', amount: '-₹8,500.00', color: 'slate' },
              { label: 'Referral Bonus (L1)', time: '2d ago', amount: '+₹1,200.00', color: 'emerald' },
              { label: 'Withdrawal Processed', time: '3d ago', amount: '-₹5,000.00', color: 'rose' },
            ].map((activity, i) => (
              <div key={i} className="flex items-center justify-between group">
                <div className="flex items-center gap-4">
                  <div className={`w-2 h-2 rounded-full bg-${activity.color}-500`}></div>
                  <div>
                    <p className="text-sm font-medium text-slate-100">{activity.label}</p>
                    <p className="text-xs text-slate-500">{activity.time}</p>
                  </div>
                </div>
                <span className={`text-sm font-bold ${activity.amount.startsWith('+') ? 'text-emerald-500' : 'text-slate-400'}`}>
                  {activity.amount}
                </span>
              </div>
            ))}
          </div>
          <button className="w-full mt-8 py-3 rounded-xl border border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800/50 transition-all font-medium">
            View All Transactions
          </button>
        </div>
      </div>
    </div>
  );
};

export default DashboardView;
